location /OAB {
	proxy_pass https://gromoxhttp;
	brotli off;
	gzip off;
	proxy_request_buffering off;
	proxy_buffering off;
	error_log /var/log/nginx/nginx-oab-error.log;
	access_log /var/log/nginx/nginx-oab-access.log;
}
